name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses || true

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          command: android debug
          buildozer-version: master

      - uses: actions/upload-artifact@v4
        with:
          name: snake-apk
          path: bin/*.apk

